In [8]:
import pandas as pd
from sklearn import datasets

In [11]:
iris=datasets.load_iris()

In [12]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [13]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [16]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [30]:
from sklearn import svm

In [34]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')

In [36]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [38]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [39]:
cross_val_score(svm.SVC(kernel='poly',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [40]:
cross_val_score(svm.SVC(kernel='sigmoid',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.33333333, 0.1       , 0.        , 0.03333333, 0.        ])

In [56]:
import numpy as np
kernels = ['rbf', 'linear','poly','sigmoid']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'poly_1': 0.9666666666666666,
 'poly_10': 0.9666666666666666,
 'poly_20': 0.9533333333333334,
 'sigmoid_1': 0.09333333333333334,
 'sigmoid_10': 0.09333333333333334,
 'sigmoid_20': 0.09333333333333334}

In [64]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel':['rbf','linear','ploy']
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)


C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
15 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Humaina\anaconda3\Lib\site

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'ploy']})

In [66]:
clf.cv_results_

{'mean_fit_time': array([0.00220013, 0.00130773, 0.00026617, 0.00121393, 0.00139718,
        0.00088453, 0.00138931, 0.00118203, 0.00019956]),
 'std_fit_time': array([0.00098541, 0.00097233, 0.00038756, 0.00039291, 0.00049024,
        0.00015467, 0.00046696, 0.00038778, 0.00039911]),
 'mean_score_time': array([0.00101566, 0.00079837, 0.        , 0.00060272, 0.00100942,
        0.        , 0.00141439, 0.0006031 , 0.        ]),
 'std_score_time': array([8.45918634e-04, 3.99815392e-04, 0.00000000e+00, 4.92159452e-04,
        1.53215429e-05, 0.00000000e+00, 4.86366295e-04, 4.92467056e-04,
        0.00000000e+00]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'ploy', 'rbf', 'linear', 'ploy',
                    'rbf', 'linear', 'ploy'],
              mask=[False, Fa

In [67]:
df=pd.DataFrame(clf.cv_results_)

In [68]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002200      0.000985         0.001016        0.000846       1   
1       0.001308      0.000972         0.000798        0.000400       1   
2       0.000266      0.000388         0.000000        0.000000       1   
3       0.001214      0.000393         0.000603        0.000492      10   
4       0.001397      0.000490         0.001009        0.000015      10   
5       0.000885      0.000155         0.000000        0.000000      10   
6       0.001389      0.000467         0.001414        0.000486      20   
7       0.001182      0.000388         0.000603        0.000492      20   
8       0.000200      0.000399         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2         ploy     {'C': 1, 'kernel': 'ploy'}                NaN   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
5         ploy    {'C': 10, 'kernel': 'ploy'}                NaN   
6          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
7       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
8         ploy    {'C': 20, 'kernel': 'ploy'}                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                NaN                NaN                NaN                NaN   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                NaN                NaN                NaN                NaN   
6                1.0           0.900000           0.966667                1.0   
7                1.0           0.900000           0.933333                1.0   
8                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2              NaN             NaN                7  
3         0.980000        0.016330                1  
4         0.973333        0.038873                4  
5              NaN             NaN                7  
6         0.966667        0.036515                5  
7         0.966667        0.042164                6  
8              NaN             NaN                7

In [69]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2       1         ploy              NaN
3      10          rbf         0.980000
4      10       linear         0.973333
5      10         ploy              NaN
6      20          rbf         0.966667
7      20       linear         0.966667
8      20         ploy              NaN

In [70]:
clf.best_score_

0.9800000000000001

In [71]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [73]:
from sklearn.model_selection import RandomizedSearchCV

In [77]:
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},
 cv=5,return_train_score=False, n_iter=3)

In [78]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [79]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1       1       linear         0.980000
2      10          rbf         0.980000