In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [6]:
from sklearn.model_selection import cross_val_score

In [7]:
iris=load_iris()

In [8]:
x=iris.data
y=iris.target

In [11]:
score_logistic=cross_val_score(LogisticRegression(),x,y)
score_svc=cross_val_score(SVC(),x,y)
score_rf=cross_val_score(RandomForestClassifier(),x,y)

C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
score_logistic

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [13]:
score_svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [14]:
score_rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [15]:
np.average(score_logistic)

0.9733333333333334

In [16]:
np.average(score_svc)

0.9666666666666666

In [17]:
np.average(score_rf)

0.9666666666666668