In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
x=digits.data
y=digits.target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [6]:
model=LogisticRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9583333333333334

In [15]:
model=SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9944444444444445

In [14]:
model=RandomForestClassifier(n_estimators=80)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9861111111111112

# KFold Cross Validation


In [17]:
from sklearn.model_selection import KFold

In [18]:
folds=KFold(n_splits=3)

In [19]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [20]:
score_logistic=[]
score_svc=[]
score_random_forest=[]

In [21]:
x=digits.data
y=digits.target

In [22]:
for train_index,test_index in folds.split(x,y):
    X_train,X_test,y_train,y_test=x[train_index],x[test_index],y[train_index],y[test_index]
    score_logistic.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    score_svc.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_random_forest.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [23]:
score_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [24]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [25]:
score_random_forest

[0.9382303839732888, 0.9549248747913188, 0.9215358931552587]

In [26]:
import numpy as np

In [31]:
np.average(score_logistic)

0.9265442404006677

In [29]:
np.average(score_svc)

0.9677239844184752

In [30]:
np.average(score_random_forest)

0.9382303839732887

# Cross_Val_Score Function

In [32]:
from sklearn.model_selection import cross_val_score

In [35]:
logistic_score=cross_val_score(LogisticRegression(),x,y)

C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Humaina\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [36]:
svc_score=cross_val_score(SVC(),x,y)

In [37]:
random_forest=cross_val_score(RandomForestClassifier(),x,y)

In [38]:
logistic_score

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
svc_score

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
random_forest

array([0.93333333, 0.89722222, 0.95264624, 0.96935933, 0.91922006])

In [41]:
np.average(logistic_score)

0.9137650882079852

In [42]:
np.average(svc_score)

0.9632838130609718

In [43]:
np.average(random_forest)

0.9343562364593005