In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [85]:
import pandas as pd

In [86]:
carPrice=pd.read_csv('/content/drive/MyDrive/DSPractical/carprices.csv')

In [87]:
carPrice

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [88]:
dummies=pd.get_dummies(carPrice['Car Model'])

In [89]:
merged=pd.concat([carPrice,dummies],axis='columns')

In [90]:
final_df=merged.drop(['Car Model','Audi A5'] , axis='columns')

In [91]:
final_df

Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1

In [92]:
from sklearn.linear_model import LinearRegression

In [93]:
model=LinearRegression()

In [94]:
x=final_df.drop('Sell Price($)',axis='columns')

In [95]:
y=final_df['Sell Price($)']

In [96]:
model.fit(x,y)

LinearRegression()

In [97]:
model.predict([[45000,4,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])

In [ ]:
model.predict([[86000,7,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313219])

In [98]:
model.score(x,y)

0.9417050937281083

**Pre Processing One Hot Encoding**

In [99]:
dfle=carPrice

In [101]:
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [102]:
dfle.dtypes

Car Model        object
Mileage           int64
Sell Price($)     int64
Age(yrs)          int64
dtype: object

In [103]:
dfle['Car Model'].unique()

array(['BMW X5', 'Audi A5', 'Mercedez Benz C class'], dtype=object)

In [104]:
from sklearn.preprocessing import OneHotEncoder

In [105]:
ohe=OneHotEncoder()

In [109]:
feature_array=ohe.fit_transform(dfle[['Car Model']]).toarray()

In [111]:
feature_labels=ohe.categories_

In [113]:
import numpy as np

In [115]:
np.array([feature_labels]).ravel()

array(['Audi A5', 'BMW X5', 'Mercedez Benz C class'], dtype=object)

In [118]:
df=pd.DataFrame(feature_array,columns=feature_labels)

In [119]:
df

Audi A5 BMW X5 Mercedez Benz C class
0      0.0    1.0                   0.0
1      0.0    1.0                   0.0
2      0.0    1.0                   0.0
3      0.0    1.0                   0.0
4      0.0    1.0                   0.0
5      1.0    0.0                   0.0
6      1.0    0.0                   0.0
7      1.0    0.0                   0.0
8      1.0    0.0                   0.0
9      0.0    0.0                   1.0
10     0.0    0.0                   1.0
11     0.0    0.0                   1.0
12     0.0    0.0                   1.0

In [120]:
final_df=pd.concat([df,dfle],axis=1)

In [121]:
final_df

(Audi A5,)  (BMW X5,)  (Mercedez Benz C class,)              Car Model  \
0          0.0        1.0                       0.0                 BMW X5   
1          0.0        1.0                       0.0                 BMW X5   
2          0.0        1.0                       0.0                 BMW X5   
3          0.0        1.0                       0.0                 BMW X5   
4          0.0        1.0                       0.0                 BMW X5   
5          1.0        0.0                       0.0                Audi A5   
6          1.0        0.0                       0.0                Audi A5   
7          1.0        0.0                       0.0                Audi A5   
8          1.0        0.0                       0.0                Audi A5   
9          0.0        0.0                       1.0  Mercedez Benz C class   
10         0.0        0.0                       1.0  Mercedez Benz C class   
11         0.0        0.0                       1.0  Mercedez Benz C class   
12         0.0        0.0                       1.0  Mercedez Benz C class   

    Mileage  Sell Price($)  Age(yrs)  
0     69000          18000         6  
1     35000          34000         3  
2     57000          26100         5  
3     22500          40000         2  
4     46000          31500         4  
5     59000          29400         5  
6     52000          32000         5  
7     72000          19300         6  
8     91000          12000         8  
9     67000          22000         6  
10    83000          20000         7  
11    79000          21000         7  
12    59000          33000         5

In [122]:
final_df.drop(['Car Model'],axis=1,inplace=True)

In [123]:
final_df

(Audi A5,)  (BMW X5,)  (Mercedez Benz C class,)  Mileage  Sell Price($)  \
0          0.0        1.0                       0.0    69000          18000   
1          0.0        1.0                       0.0    35000          34000   
2          0.0        1.0                       0.0    57000          26100   
3          0.0        1.0                       0.0    22500          40000   
4          0.0        1.0                       0.0    46000          31500   
5          1.0        0.0                       0.0    59000          29400   
6          1.0        0.0                       0.0    52000          32000   
7          1.0        0.0                       0.0    72000          19300   
8          1.0        0.0                       0.0    91000          12000   
9          0.0        0.0                       1.0    67000          22000   
10         0.0        0.0                       1.0    83000          20000   
11         0.0        0.0                       1.0    79000          21000   
12         0.0        0.0                       1.0    59000          33000   

    Age(yrs)  
0          6  
1          3  
2          5  
3          2  
4          4  
5          5  
6          5  
7          6  
8          8  
9          6  
10         7  
11         7  
12         5

In [141]:
x=final_df.drop(['Sell Price($)'],axis=1).values
y=final_df['Sell Price($)'].values

In [125]:
from sklearn.linear_model import LinearRegression

In [139]:
model=LinearRegression()

In [142]:
model.fit(x,y)

LinearRegression()

In [143]:
model.predict([[0,0,1,45000,4]])

array([36991.31721061])

In [144]:
model.predict([[0,1,0,86000,7]])

array([11080.74313219])

In [145]:
model.score(x,y)

0.9417050937281083